import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./provider";
import { AuthProvider } from "./_context/Authcontext";
import { DoctorAuthProvider } from "./_context/Doctorcontext";
import { CopilotKit } from "@copilotkit/react-core";
import { CopilotPopup } from "@copilotkit/react-ui";
import "@copilotkit/react-ui/styles.css"; 




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers><DoctorAuthProvider><AuthProvider><CopilotKit publicApiKey="ck_pub_e64926d648343785d8dab62d4c920541"> {children}
          
          
        <CopilotPopup
            labels={{
              title: "Doc Assistant",
              initial: "Hello! How can I assist you with your sickness?",
            }}
            className="neobrutalist-copilot z-100"
          />
          </CopilotKit></AuthProvider></DoctorAuthProvider></Providers>
      </body>
    </html>
  );
}
